import path from "node:path";
import {
  registerHandler,
  type StepContext,
  type StepHandler,
} from "@/services/worker/types/service.ts";
import { Handlers } from "@/services/worker/constants/handlers.ts";
import { env } from "@/shared/utils/env.ts";
import type { DataValue, DataValueSet } from "@/services/worker/types/data.ts";
import { getPredictionResult, getPredictionSetup } from "@/services/worker/utils/chap.ts";
import {
  predictionDataDownloadConfigSchema,
  type PredictionDataDownloadConfig,
} from "@/services/worker/services/handlers/predictionDataDownload/schemas/config.ts";
import { uniqueDataValueSetFilename } from "@/services/worker/utils/dataValueSetFile.ts";
import { toQuantileValue } from "@/services/worker/services/handlers/predictionDataDownload/utils/quantileKeys.ts";

/**
 * Handler: prediction-data-download
 *
 * Fetches forecast rows from CHAP GET /v1/analytics/prediction-entry/{resultId}
 * (using `result` from prediction-poll), maps each row's quantile to a DHIS2 data
 * element, writes a DataValueSet JSON file under OUTPUTS_DIR with an autogenerated unique
 * basename for dhis2-data-upload.
 *
 * The mapping comes from handlerConfig.dataElementIds, or — when that is left out — from the
 * quantile targets of the prediction setup the run came from, which record the same thing.
 *
 * Expected input (e.g. from prediction-poll):
 * { jobId: string; result: string; status?: string; predictionSetupId?: number | null }
 *
 * Expected handlerConfig: see predictionDataDownloadConfigSchema.
 *
 * Output: { jobId, filename, count }
 */
export const predictionDataDownload: StepHandler = {
  async execute(ctx) {
    await ctx.log("INFO", "Parsing prediction data download config");
    const configParse = predictionDataDownloadConfigSchema.safeParse(ctx.handlerConfig);

    if (!configParse.success) {
      await ctx.log("ERROR", configParse.error.message);
      throw configParse.error;
    }
    const config = configParse.data;

    const input = ctx.input as {
      jobId?: string;
      result: string;
      status: string;
      predictionSetupId?: number | null;
    };
    const jobId = input?.jobId;
    if (!jobId) {
      throw new Error(
        "prediction-data-download requires { jobId } from the previous step's output"
      );
    }

    if (!input.result) {
      throw new Error(
        "prediction-data-download requires { result } from the previous step's output"
      );
    }

    const mapping = await resolveQuantileMapping({ ctx, config, input });
    const quantiles = Object.keys(mapping);

    const task = await ctx.tasks.startTask("fetch-prediction-result", { jobId, quantiles });

    let chapResult;
    try {
      chapResult = await getPredictionResult({ resultId: input.result, quantiles });
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      await task.fail(error);
      throw error;
    }

    const dataValues: DataValue[] = [];

    for (const row of chapResult) {
      const dhis2De = mapping[String(row.quantile)];
      if (!dhis2De) {
        const error = new Error(
          `Unmapped CHAP quantile "${row.quantile}" — add it to handlerConfig.dataElementIds or to the prediction setup's quantile targets`
        );
        await task.fail(error);
        throw error;
      }
      dataValues.push({
        dataElement: dhis2De,
        orgUnit: row.orgUnit,
        period: row.period,
        value: String(Math.round(row.value)),
      });
    }

    const payload: DataValueSet = {
      dataValues,
    };

    const outputFilename = uniqueDataValueSetFilename("chap-prediction");
    const filePath = path.resolve(env.OUTPUTS_DIR, outputFilename);
    try {
      await Bun.write(filePath, JSON.stringify(payload));
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      await task.fail(error);
      throw error;
    }

    const result = {
      jobId,
      filename: outputFilename,
      count: dataValues.length,
    };

    await task.succeed({ filePath, ...result });
    await ctx.log("INFO", "Prediction data written as DataValueSet", result);

    return result;
  },
};

/**
 * Chooses which quantile → data element mapping the run writes with. An explicit
 * handlerConfig wins; otherwise the prediction setup's own quantile targets are used, so the
 * mapping lives in one place.
 */
async function resolveQuantileMapping({
  ctx,
  config,
  input,
}: {
  ctx: StepContext;
  config: PredictionDataDownloadConfig;
  input: { predictionSetupId?: number | null };
}): Promise<Record<string, string>> {
  const configured = config.dataElementIds ?? {};
  if (Object.keys(configured).length > 0) {
    return normaliseQuantileKeys(configured).byQuantile;
  }

  const predictionSetupId = input.predictionSetupId;
  if (!predictionSetupId) {
    throw new Error(
      "prediction-data-download has no quantile mapping: set handlerConfig.dataElementIds, or run it after a prediction step that uses a CHAP prediction setup"
    );
  }

  const setup = await getPredictionSetup(predictionSetupId);
  const { byQuantile, skipped } = normaliseQuantileKeys(
    Object.fromEntries(
      setup.quantileTargets.map(({ quantile, dataElementId }) => [quantile, dataElementId] as const)
    )
  );

  if (Object.keys(byQuantile).length === 0) {
    throw new Error(
      `Prediction setup "${setup.name}" has no forecast quantile targets; add them in CHAP or set handlerConfig.dataElementIds`
    );
  }

  if (skipped.length > 0) {
    await ctx.log("INFO", "Ignoring prediction setup targets that are not forecast quantiles", {
      predictionSetupId,
      targets: skipped,
    });
  }

  await ctx.log("INFO", "Using quantile targets from the prediction setup", {
    predictionSetupId,
    quantiles: Object.keys(byQuantile),
  });

  return byQuantile;
}

function normaliseQuantileKeys(mapping: Record<string, string>): {
  byQuantile: Record<string, string>;
  skipped: string[];
} {
  const byQuantile: Record<string, string> = {};
  const skipped: string[] = [];

  for (const [key, dataElementId] of Object.entries(mapping)) {
    const quantile = toQuantileValue(key);
    if (quantile === null) {
      skipped.push(key);
      continue;
    }
    byQuantile[quantile] = dataElementId;
  }

  return { byQuantile, skipped };
}

registerHandler(Handlers.PREDICTION_DATA_DOWNLOAD, predictionDataDownload);
