import path from "node:path";
import { registerHandler, type StepHandler } from "@/services/worker/types/service.ts";
import { Handlers } from "@/services/worker/constants/handlers.ts";
import { env } from "@/shared/utils/env.ts";
import type { DataValue, DataValueSet } from "@/services/worker/types/data.ts";
import { getPredictionResult } from "@/services/worker/utils/chap.ts";
import { predictionDataDownloadConfigSchema } from "@/services/worker/services/handlers/predictionDataDownload/schemas/config.ts";
import { uniqueDataValueSetFilename } from "@/services/worker/utils/dataValueSetFile.ts";

/**
 * Handler: prediction-data-download
 *
 * Fetches forecast rows from CHAP GET /v1/analytics/prediction-entry/{resultId}
 * (using `result` from prediction-poll), maps each row's quantile to a DHIS2 data
 * element via handlerConfig.dataElementIds, writes a DataValueSet JSON file under
 * OUTPUTS_DIR with an autogenerated unique basename for dhis2-data-upload.
 *
 * Expected input (e.g. from prediction-poll): { jobId: string; result: string; status?: string }
 *
 * Expected handlerConfig: see predictionDataDownloadConfigSchema.
 *
 * Output: { jobId, filename, count }
 */
export const predictionDataDownload: StepHandler = {
  async execute(ctx) {
    await ctx.log("INFO", "Parsing prediction data download config");
    const configParse = predictionDataDownloadConfigSchema.safeParse(ctx.handlerConfig);

    if (!configParse.success) {
      await ctx.log("ERROR", configParse.error.message);
      throw configParse.error;
    }
    const config = configParse.data;

    const input = ctx.input as { jobId?: string; result: string; status: string };
    const jobId = input?.jobId;
    if (!jobId) {
      throw new Error(
        "prediction-data-download requires { jobId } from the previous step's output"
      );
    }

    if (!input.result) {
      throw new Error(
        "prediction-data-download requires { result } from the previous step's output"
      );
    }

    const task = await ctx.tasks.startTask("fetch-prediction-result", { jobId });

    let chapResult;
    try {
      chapResult = await getPredictionResult({ resultId: input.result });
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      await task.fail(error);
      throw error;
    }

    const mapping = config.dataElementIds;
    const dataValues: DataValue[] = [];

    for (const row of chapResult) {
      const dhis2De = mapping[row.quantile];
      if (!dhis2De) {
        const error = new Error(
          `Unmapped CHAP dataElement "${row.quantile}" — add it to handlerConfig.dataElementIds`
        );
        await task.fail(error);
        throw error;
      }
      dataValues.push({
        dataElement: dhis2De,
        orgUnit: row.orgUnit,
        period: row.period,
        value: String(Math.round(row.value)),
      });
    }

    const payload: DataValueSet = {
      dataValues,
    };

    const outputFilename = uniqueDataValueSetFilename("chap-prediction");
    const filePath = path.resolve(env.OUTPUTS_DIR, outputFilename);
    try {
      await Bun.write(filePath, JSON.stringify(payload));
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      await task.fail(error);
      throw error;
    }

    const result = {
      jobId,
      filename: outputFilename,
      count: dataValues.length,
    };

    await task.succeed({ filePath, ...result });
    await ctx.log("INFO", "Prediction data written as DataValueSet", result);

    return result;
  },
};

registerHandler(Handlers.PREDICTION_DATA_DOWNLOAD, predictionDataDownload);
