
connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://dhis2-db/dhis
connection.username = admin
connection.password = district

monitoring.api.enabled = off
monitoring.jvm.enabled = off
monitoring.dbpool.enabled = off
monitoring.hibernate.enabled = off
monitoring.uptime.enabled = off
monitoring.cpu.enabled = off

system.audit.enabled = off
route.remote_servers_allowed = http://*