/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Index
         * @description Return openEO capabilities (JSON) or the landing page (HTML).
         */
        get: operations["read_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return health status for container health checks.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Info
         * @description Return application version and environment info.
         */
        get: operations["info_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/openeo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Well Known Openeo
         * @description OpenEO service discovery — lets clients find the versioned API URL.
         */
        get: operations["well_known_openeo__well_known_openeo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credentials/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Credentials Oidc
         * @description Return OIDC authentication providers (empty = open/anonymous access).
         */
        get: operations["credentials_oidc_credentials_oidc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file_formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * File Formats
         * @description Return supported input and output file formats.
         */
        get: operations["file_formats_file_formats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Types
         * @description Return supported secondary web service types (none currently).
         */
        get: operations["service_types_service_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return basic account info for this open/anonymous backend.
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stac": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stac Landing
         * @description Return the STAC catalog landing page.
         */
        get: operations["get_stac_landing_stac_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stac/catalog.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stac Catalog Json
         * @description Return the STAC catalog landing page (catalog.json alias).
         */
        get: operations["get_stac_catalog_json_stac_catalog_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stac/collections/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stac Collection
         * @description Return one STAC collection document.
         */
        get: operations["get_stac_collection_stac_collections__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Collections
         * @description Return all published collections (openEO + STAC compatible).
         */
        get: operations["list_collections_collections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection
         * @description Return one published collection.
         */
        get: operations["get_collection_collections__collection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Return all openEO jobs.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new openEO job.
         */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Return one openEO job.
         */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Delete a job and its results.
         */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Job
         * @description Update job metadata (title, description, process, etc.).
         */
        patch: operations["update_job_jobs__job_id__patch"];
        trace?: never;
    };
    "/jobs/{job_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results
         * @description Return result links for a finished job.
         */
        get: operations["get_results_jobs__job_id__results_get"];
        put?: never;
        /**
         * Start Job
         * @description Queue a job for processing.
         */
        post: operations["start_job_jobs__job_id__results_post"];
        /**
         * Cancel Job
         * @description Cancel a running or queued job.
         */
        delete: operations["cancel_job_jobs__job_id__results_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/results/result.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Geojson Result
         * @description Serve the GeoJSON result file for a finished batch job.
         */
        get: operations["download_geojson_result_jobs__job_id__results_result_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/results/result.zarr/{zarr_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Zarr Chunk
         * @description Serve one file from within the Zarr result store (chunk or metadata).
         */
        get: operations["download_zarr_chunk_jobs__job_id__results_result_zarr__zarr_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/results/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Result File
         * @description Serve a result file (NetCDF, GeoTIFF, PNG, CSV, GeoParquet) for a finished batch job.
         */
        get: operations["download_result_file_jobs__job_id__results__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process_graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflows
         * @description Return all stored workflows (user-defined processes).
         */
        get: operations["list_workflows_process_graphs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/process_graphs/{process_graph_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow
         * @description Return one workflow (user-defined process).
         */
        get: operations["get_workflow_process_graphs__process_graph_id__get"];
        /**
         * Put Workflow
         * @description Store or replace a workflow (user-defined process).
         */
        put: operations["put_workflow_process_graphs__process_graph_id__put"];
        post?: never;
        /**
         * Delete Workflow
         * @description Delete a workflow (user-defined process).
         */
        delete: operations["delete_workflow_process_graphs__process_graph_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Synchronous
         * @description Execute a process graph synchronously and return the result.
         *
         *     Returns JSON for scalar/dict results, or an exported file for
         *     synchronously-supported non-Zarr raster/vector formats.
         */
        post: operations["execute_synchronous_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Extent
         * @description Return the configured extent for this Open Climate Service instance.
         */
        get: operations["get_extent_extent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dataset Templates
         * @description Return the available dataset templates from the registry.
         */
        get: operations["list_dataset_templates_dataset_templates__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset-templates/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Template
         * @description Get a single dataset template by ID with derived coverage metadata.
         */
        get: operations["get_dataset_template_dataset_templates__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List managed datasets.
         */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset
         * @description Get managed dataset metadata and available versions.
         */
        get: operations["get_dataset_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Artifact File
         * @description Download the primary saved file for a dataset when available.
         */
        get: operations["download_artifact_file_datasets__dataset_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestions/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingestion Job
         * @description Return the status of an async ingestion or sync job.
         */
        get: operations["get_ingestion_job_ingestions_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Ingestion Job
         * @description Request cooperative cancellation for an async ingestion or sync job.
         */
        delete: operations["cancel_ingestion_job_ingestions_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ingestions
         * @description List ingestion run records for operational and admin use.
         */
        get: operations["list_ingestions_ingestions_get"];
        put?: never;
        /**
         * Create Ingestion
         * @description Create or update a managed dataset from a dataset template and configured extent.
         *
         *     Pass ``Prefer: respond-async`` to queue the ingestion as a background job and
         *     return immediately with 202 + ``Location: /ingestions/jobs/{id}``.
         */
        post: operations["create_ingestion_ingestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestions/{ingestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingestion
         * @description Return the managed dataset view created for a given ingestion.
         */
        get: operations["get_ingestion_ingestions__ingestion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zarr/{dataset_id}/{relative_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Canonical Zarr Store File
         * @description Serve canonical Zarr store content for a managed dataset.
         */
        get: operations["get_canonical_zarr_store_file_zarr__dataset_id___relative_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get Canonical Zarr Store File
         * @description Serve canonical Zarr store content for a managed dataset.
         */
        head: operations["get_canonical_zarr_store_file_zarr__dataset_id___relative_path__get"];
        patch?: never;
        trace?: never;
    };
    "/icechunk/{dataset_id}/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Icechunk Store File
         * @description Serve a raw Icechunk store file for native SDK access.
         *
         *     Enables clients to open the store directly with::
         *
         *         import icechunk, zarr
         *
         *         repo = icechunk.Repository.open(icechunk.http_storage("http://<host>/icechunk/<dataset_id>/"))
         *         ds = zarr.open(repo.readonly_session("main").store, zarr_format=3)
         */
        get: operations["serve_icechunk_store_file_icechunk__dataset_id___file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Serve Icechunk Store File
         * @description Serve a raw Icechunk store file for native SDK access.
         *
         *     Enables clients to open the store directly with::
         *
         *         import icechunk, zarr
         *
         *         repo = icechunk.Repository.open(icechunk.http_storage("http://<host>/icechunk/<dataset_id>/"))
         *         ds = zarr.open(repo.readonly_session("main").store, zarr_format=3)
         */
        head: operations["serve_icechunk_store_file_icechunk__dataset_id___file_path__get"];
        patch?: never;
        trace?: never;
    };
    "/sync/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Dataset
         * @description Sync a managed dataset forward from its latest available time step.
         *
         *     Pass ``Prefer: respond-async`` to queue the sync as a background job and
         *     return immediately with 202 + ``Location: /ingestions/jobs/{id}``.
         */
        post: operations["sync_dataset_sync__dataset_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/{dataset_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan Sync Dataset
         * @description Return the sync plan for a managed dataset without starting a download.
         */
        get: operations["plan_sync_dataset_sync__dataset_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schedules
         * @description Return configured schedules with process-local runtime status.
         */
        get: operations["list_schedules_schedules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Processes
         * @description Return all available openEO processes.
         */
        get: operations["list_processes_processes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processes/{process_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Process Spec
         * @description Return one openEO process description by id.
         */
        get: operations["get_process_spec_processes__process_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppInfo
         * @description Application version and environment info.
         */
        AppInfo: {
            /** App Version */
            app_version: string;
            /** Python Version */
            python_version: string;
            /** Uvicorn Version */
            uvicorn_version: string;
            /**
             * Read Only
             * @default false
             */
            read_only: boolean;
        };
        /**
         * ArtifactCoverage
         * @description Artifact coverage metadata.
         */
        ArtifactCoverage: {
            /** @description Covered spatial extent of the managed dataset. */
            spatial: components["schemas"]["CoverageSpatial"];
            /** @description Spatial extent in WGS84. None for WGS84 instances or legacy records. */
            spatial_wgs84?: components["schemas"]["CoverageSpatial"] | null;
            /** @description Covered temporal extent of the managed dataset. */
            temporal: components["schemas"]["CoverageTemporal"];
        };
        /**
         * ArtifactFormat
         * @description Supported stored artifact formats.
         * @enum {string}
         */
        ArtifactFormat: "zarr" | "netcdf" | "icechunk";
        /**
         * ArtifactRequestScope
         * @description Original request parameters used to create an artifact.
         */
        ArtifactRequestScope: {
            /**
             * Start
             * @description Requested start period (None for a non-temporal dataset, e.g. a climatology).
             */
            start?: string | null;
            /**
             * End
             * @description Requested end period for the ingestion or sync operation.
             */
            end?: string | null;
            /**
             * Bbox
             * @description Requested bounding box when the artifact was created.
             */
            bbox?: [
                number,
                number,
                number,
                number
            ] | null;
        };
        /**
         * CheckOutcome
         * @description Outcome of one scheduled dataset check.
         * @enum {string}
         */
        CheckOutcome: "submitted" | "not_materialized" | "already_running" | "read_only" | "error";
        /**
         * CoverageSpatial
         * @description Spatial extent summary.
         */
        CoverageSpatial: {
            /**
             * Xmin
             * @description Minimum longitude of the covered spatial extent.
             */
            xmin: number;
            /**
             * Ymin
             * @description Minimum latitude of the covered spatial extent.
             */
            ymin: number;
            /**
             * Xmax
             * @description Maximum longitude of the covered spatial extent.
             */
            xmax: number;
            /**
             * Ymax
             * @description Maximum latitude of the covered spatial extent.
             */
            ymax: number;
        };
        /**
         * CoverageTemporal
         * @description Temporal extent summary.
         *
         *     ``start``/``end`` are ``None`` for a non-temporal (ordinal) dataset such as a
         *     day-of-year climatology, which has no datetime extent.
         */
        CoverageTemporal: {
            /**
             * Start
             * @description First covered time period in dataset-native string form.
             */
            start?: string | null;
            /**
             * End
             * @description Last covered time period in dataset-native string form.
             */
            end?: string | null;
        };
        /**
         * CreateIngestionRequest
         * @description Request payload for creating or updating a managed dataset.
         */
        CreateIngestionRequest: {
            /**
             * Dataset Id
             * @description Source dataset template id from the Open Climate Service registry.
             */
            dataset_id: string;
            /**
             * Start
             * @description Start period to ingest. Required for historical datasets. May be omitted for a dataset declaring 'temporal_direction: future' (e.g. a forecast), where it means 'from now' — a fixed date would be stale by the next day.
             */
            start?: string | null;
            /**
             * End
             * @description Optional end period to ingest.
             */
            end?: string | null;
            /**
             * Overwrite
             * @description Whether to force regeneration of an existing matching artifact.
             * @default false
             */
            overwrite: boolean;
            /**
             * Publish
             * @description Whether to publish the resulting dataset.
             * @default true
             */
            publish: boolean;
        };
        /**
         * DatasetAccessLink
         * @description Access link for a managed dataset.
         */
        DatasetAccessLink: {
            /**
             * Href
             * @description Relative API path for this dataset access mode.
             */
            href: string;
            /**
             * Rel
             * @description Relationship type of the link.
             */
            rel: string;
            /**
             * Title
             * @description Human-readable label for the link target.
             */
            title: string;
        };
        /**
         * DatasetDetailRecord
         * @description Detailed native FastAPI view of a managed dataset.
         */
        DatasetDetailRecord: {
            /**
             * Dataset Id
             * @description Stable public identifier for the managed dataset.
             */
            dataset_id: string;
            /**
             * Source Dataset Id
             * @description Dataset template id from which this managed dataset was created.
             */
            source_dataset_id: string;
            /**
             * Dataset Name
             * @description Full display name of the dataset.
             */
            dataset_name: string;
            /**
             * Short Name
             * @description Short display name of the dataset.
             */
            short_name?: string | null;
            /**
             * Variable
             * @description Primary raster variable stored in the dataset.
             */
            variable: string;
            /**
             * Period Type
             * @description Temporal period type of the dataset, for example daily or yearly.
             */
            period_type: string;
            /**
             * Units
             * @description Units of the primary variable.
             */
            units?: string | null;
            /**
             * Resolution
             * @description Native spatial resolution summary.
             */
            resolution?: string | null;
            /**
             * Source
             * @description Upstream source name.
             */
            source?: string | null;
            /**
             * Source Url
             * @description Upstream source documentation URL.
             */
            source_url?: string | null;
            /** @description Current covered spatial and temporal extent of the dataset. */
            extent: components["schemas"]["ArtifactCoverage"];
            /**
             * Last Updated
             * Format: date-time
             * @description Timestamp when Open Climate Service last materialized or updated the dataset.
             */
            last_updated: string;
            /**
             * Links
             * @description Available API access links for this managed dataset.
             */
            links?: components["schemas"]["DatasetAccessLink"][];
            /** @description Publication summary for this managed dataset. */
            publication: components["schemas"]["DatasetPublication"];
            /**
             * Versions
             * @description Slim version history derived from internal artifact records.
             */
            versions: components["schemas"]["DatasetVersionRecord"][];
        };
        /**
         * DatasetListResponse
         * @description Envelope response for managed datasets.
         */
        DatasetListResponse: {
            /**
             * Kind
             * @description Self-describing envelope type for this collection response.
             * @default DatasetList
             * @example DatasetList
             */
            kind: string;
            /**
             * Items
             * @description Managed datasets available in this Open Climate Service instance.
             * @example [
             *       {
             *         "dataset_id": "chirps3_precipitation_daily_sle",
             *         "dataset_name": "Total precipitation (CHIRPS3)",
             *         "extent": {
             *           "spatial": {
             *             "xmax": -10.1,
             *             "xmin": -13.5,
             *             "ymax": 10,
             *             "ymin": 6.9
             *           },
             *           "temporal": {
             *             "end": "2024-01-31",
             *             "start": "2024-01-01"
             *           }
             *         },
             *         "last_updated": "2026-03-27T08:40:24.344473Z",
             *         "links": [
             *           {
             *             "href": "/datasets/chirps3_precipitation_daily_sle",
             *             "rel": "self",
             *             "title": "Dataset detail"
             *           },
             *           {
             *             "href": "/zarr/chirps3_precipitation_daily_sle",
             *             "rel": "zarr",
             *             "title": "Zarr store"
             *           }
             *         ],
             *         "period_type": "daily",
             *         "publication": {
             *           "published_at": "2026-03-27T08:40:24.346357Z",
             *           "status": "published"
             *         },
             *         "resolution": "5 km x 5 km",
             *         "short_name": "Total precipitation",
             *         "source": "CHIRPS v3",
             *         "source_dataset_id": "chirps3_precipitation_daily",
             *         "source_url": "https://www.chc.ucsb.edu/data/chirps3",
             *         "units": "mm",
             *         "variable": "precip"
             *       }
             *     ]
             */
            items?: components["schemas"]["DatasetRecord"][];
        };
        /**
         * DatasetPublication
         * @description Public publication summary for a managed dataset.
         */
        DatasetPublication: {
            /** @description Publication state of the dataset in the OGC-facing layer. */
            status: components["schemas"]["PublicationStatus"];
            /**
             * Published At
             * @description Timestamp when the dataset was last published.
             */
            published_at?: string | null;
        };
        /**
         * DatasetRecord
         * @description Native FastAPI view of a managed dataset.
         */
        DatasetRecord: {
            /**
             * Dataset Id
             * @description Stable public identifier for the managed dataset.
             */
            dataset_id: string;
            /**
             * Source Dataset Id
             * @description Dataset template id from which this managed dataset was created.
             */
            source_dataset_id: string;
            /**
             * Dataset Name
             * @description Full display name of the dataset.
             */
            dataset_name: string;
            /**
             * Short Name
             * @description Short display name of the dataset.
             */
            short_name?: string | null;
            /**
             * Variable
             * @description Primary raster variable stored in the dataset.
             */
            variable: string;
            /**
             * Period Type
             * @description Temporal period type of the dataset, for example daily or yearly.
             */
            period_type: string;
            /**
             * Units
             * @description Units of the primary variable.
             */
            units?: string | null;
            /**
             * Resolution
             * @description Native spatial resolution summary.
             */
            resolution?: string | null;
            /**
             * Source
             * @description Upstream source name.
             */
            source?: string | null;
            /**
             * Source Url
             * @description Upstream source documentation URL.
             */
            source_url?: string | null;
            /** @description Current covered spatial and temporal extent of the dataset. */
            extent: components["schemas"]["ArtifactCoverage"];
            /**
             * Last Updated
             * Format: date-time
             * @description Timestamp when Open Climate Service last materialized or updated the dataset.
             */
            last_updated: string;
            /**
             * Links
             * @description Available API access links for this managed dataset.
             */
            links?: components["schemas"]["DatasetAccessLink"][];
            /** @description Publication summary for this managed dataset. */
            publication: components["schemas"]["DatasetPublication"];
        };
        /**
         * DatasetVersionRecord
         * @description Version summary as exposed from a dataset detail view.
         */
        DatasetVersionRecord: {
            /**
             * Created At
             * Format: date-time
             * @description Timestamp when this dataset version was created.
             */
            created_at: string;
            /** @description Stored format of this dataset version. */
            format: components["schemas"]["ArtifactFormat"];
            /** @description Covered spatial and temporal extent for this dataset version. */
            coverage: components["schemas"]["ArtifactCoverage"];
            /** @description Original request scope that produced this version, when available. */
            request_scope?: components["schemas"]["ArtifactRequestScope"] | null;
        };
        /**
         * ExtentRecord
         * @description Configured spatial extent for this Open Climate Service instance.
         */
        ExtentRecord: {
            /**
             * Name
             * @description Human-readable name of the extent.
             */
            name?: string | null;
            /**
             * Description
             * @description Optional descriptive text for the extent.
             */
            description?: string | null;
            /**
             * Bbox
             * @description Configured bounding box for the extent as xmin, ymin, xmax, ymax.
             */
            bbox: [
                number,
                number,
                number,
                number
            ];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Health check response.
         */
        HealthStatus: {
            status: components["schemas"]["Status"];
        };
        /**
         * IngestionListResponse
         * @description Envelope response for ingestion run records.
         */
        IngestionListResponse: {
            /**
             * Kind
             * @description Self-describing envelope type for this collection response.
             * @default IngestionList
             * @example IngestionList
             */
            kind: string;
            /**
             * Items
             * @description Ingestion run records available in this Open Climate Service instance.
             */
            items?: components["schemas"]["IngestionResponse"][];
        };
        /**
         * IngestionResponse
         * @description Response returned after creating or looking up a managed dataset via ingestion.
         */
        IngestionResponse: {
            /**
             * Ingestion Id
             * @description Identifier of the ingestion event.
             */
            ingestion_id: string;
            /**
             * Status
             * @description Execution status of the ingestion request.
             */
            status: string;
            /** @description Managed dataset summary. None for async requests. */
            dataset?: components["schemas"]["DatasetRecord"] | null;
        };
        /**
         * JobError
         * @description Serialized error details for a failed job.
         */
        JobError: {
            /** Type */
            type: string;
            /** Message */
            message: string;
        };
        /**
         * JobEvent
         * @description Domain event persisted atomically with a successful native job.
         */
        JobEvent: {
            /** Type */
            type: string;
            /** Source */
            source: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Eventid */
            eventID: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /**
         * JobLink
         * @description Hypermedia link for a job resource.
         */
        JobLink: {
            /** Href */
            href: string;
            /** Rel */
            rel: string;
            /** Title */
            title?: string | null;
        };
        /**
         * JobProgress
         * @description Progress details reported by a running job.
         */
        JobProgress: {
            /** Done */
            done?: number | null;
            /** Total */
            total?: number | null;
            /** Percent */
            percent?: number | null;
            /** Message */
            message?: string | null;
        };
        /**
         * JobRecord
         * @description Persisted native job record.
         */
        JobRecord: {
            /** Jobid */
            jobID: string;
            /** Processid */
            processID: string;
            /** @default process */
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Startedat */
            startedAt?: string | null;
            /** Finishedat */
            finishedAt?: string | null;
            /**
             * Attempt
             * @default 0
             */
            attempt: number;
            /**
             * Maxattempts
             * @default 1
             */
            maxAttempts: number;
            /**
             * Executorkind
             * @default thread
             */
            executorKind: string;
            /** Request */
            request?: {
                [key: string]: unknown;
            };
            progress?: components["schemas"]["JobProgress"];
            /** Result */
            result?: unknown | null;
            /** Events */
            events?: components["schemas"]["JobEvent"][];
            error?: components["schemas"]["JobError"] | null;
            /**
             * Cancelrequested
             * @default false
             */
            cancelRequested: boolean;
            /** Retryafter */
            retryAfter?: number | null;
            /** Cursor */
            cursor?: {
                [key: string]: unknown;
            } | null;
            /** Links */
            links?: components["schemas"]["JobLink"][];
        };
        /**
         * JobStatus
         * @description Persisted lifecycle states for native jobs.
         * @enum {string}
         */
        JobStatus: "accepted" | "running" | "retrying" | "successful" | "failed" | "cancelled";
        /**
         * JobType
         * @description Native job categories.
         * @enum {string}
         */
        JobType: "process";
        /**
         * Link
         * @description Hypermedia link.
         */
        Link: {
            /** Href */
            href: string;
            /** Rel */
            rel: string;
            /** Title */
            title: string;
        };
        /**
         * OpenEOJobCreate
         * @description Request body for POST /jobs.
         */
        OpenEOJobCreate: {
            /** Process */
            process: {
                [key: string]: unknown;
            };
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Plan */
            plan?: string | null;
            /** Budget */
            budget?: number | null;
        };
        /**
         * OpenEOJobListResponse
         * @description Envelope for GET /jobs.
         */
        OpenEOJobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["OpenEOJobRecord"][];
            /** Links */
            links?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * OpenEOJobRecord
         * @description Persisted openEO job record.
         */
        OpenEOJobRecord: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Process */
            process?: {
                [key: string]: unknown;
            };
            status: components["schemas"]["OpenEOJobStatus"];
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Updated */
            updated?: string | null;
            /** Plan */
            plan?: string | null;
            /** Budget */
            budget?: number | null;
            /** Usage */
            usage?: {
                [key: string]: unknown;
            } | null;
            /** Logs */
            logs?: string | null;
            /** Links */
            links?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * OpenEOJobResults
         * @description Response for GET /jobs/{id}/results.
         */
        OpenEOJobResults: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Stac Version */
            stac_version: string;
            /** Stac Extensions */
            stac_extensions?: string[];
            /** Id */
            id: string;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
            /** Assets */
            assets?: {
                [key: string]: unknown;
            };
            /** Links */
            links?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * OpenEOJobStatus
         * @description openEO-compliant job lifecycle states.
         * @enum {string}
         */
        OpenEOJobStatus: "created" | "queued" | "running" | "finished" | "error" | "canceled";
        /**
         * OpenEOJobUpdate
         * @description Request body for PATCH /jobs/{job_id}.
         */
        OpenEOJobUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Process */
            process?: {
                [key: string]: unknown;
            } | null;
            /** Plan */
            plan?: string | null;
            /** Budget */
            budget?: number | null;
        };
        /**
         * PublicationStatus
         * @description Publication lifecycle states.
         * @enum {string}
         */
        PublicationStatus: "unpublished" | "published";
        /**
         * ScheduleListResponse
         * @description Status of the process-local scheduler and configured schedules.
         */
        ScheduleListResponse: {
            /** Enabled */
            enabled: boolean;
            /** Running */
            running: boolean;
            /** Timezone */
            timezone: string;
            /** Schedules */
            schedules?: components["schemas"]["ScheduleStatus"][];
        };
        /**
         * ScheduleStatus
         * @description Configuration and volatile runtime status for one dataset schedule.
         */
        ScheduleStatus: {
            /** Schedule Id */
            schedule_id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Cron */
            cron: string;
            /** Timezone */
            timezone: string;
            /** Publish */
            publish: boolean;
            /** Max Attempts */
            max_attempts: number;
            /** Next Check */
            next_check?: string | null;
            /** Last Check */
            last_check?: string | null;
            last_outcome?: components["schemas"]["CheckOutcome"] | null;
            /** Last Message */
            last_message?: string | null;
            /** Last Job Id */
            last_job_id?: string | null;
        };
        /**
         * StacCatalogResponse
         * @description Catalog response with flexible extension fields.
         */
        StacCatalogResponse: {
            /** Stac Version */
            stac_version: string;
            /**
             * Type
             * @constant
             */
            type: "Catalog";
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Links */
            links: components["schemas"]["StacLink"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * StacLink
         * @description Minimal STAC link representation.
         */
        StacLink: {
            /** Rel */
            rel: string;
            /** Href */
            href: string;
            /** Type */
            type?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * Status
         * @description Health check status values.
         * @enum {string}
         */
        Status: "healthy" | "degraded" | "unhealthy";
        /**
         * SyncAction
         * @description Planner-selected sync action.
         *
         *     APPEND means Open Climate Service updates an existing managed dataset by writing only
         *     the missing periods needed to reach the planned target end by extending the
         *     committed artifact store.
         * @enum {string}
         */
        SyncAction: "rematerialize" | "append" | "no_op" | "not_syncable";
        /**
         * SyncDatasetRequest
         * @description Request payload for syncing a managed dataset forward.
         */
        SyncDatasetRequest: {
            /**
             * End
             * @description Optional end period to sync through.
             */
            end?: string | null;
            /**
             * Publish
             * @description Whether to publish the resulting dataset version.
             * @default true
             */
            publish: boolean;
        };
        /**
         * SyncDetail
         * @description Structured planner output for one managed dataset sync decision.
         *
         *     This record exists so callers can see both the operational outcome and the
         *     reasoning that led to it without needing to infer that logic from status
         *     strings alone.
         */
        SyncDetail: {
            /**
             * Source Dataset Id
             * @description Source dataset template id used to plan the sync.
             */
            source_dataset_id: string;
            /** @description Sync planning mode declared by the dataset template. */
            sync_kind: components["schemas"]["SyncKind"];
            /** @description Planner-selected sync action. */
            action: components["schemas"]["SyncAction"];
            /**
             * Reason
             * @description Stable machine-readable reason for the selected action.
             */
            reason: string;
            /**
             * Message
             * @description Human-readable summary of the planned sync outcome.
             */
            message: string;
            /**
             * Current Start
             * @description First period currently covered by the managed dataset before sync.
             */
            current_start?: string | null;
            /**
             * Current End
             * @description Last period currently covered by the managed dataset before sync.
             */
            current_end?: string | null;
            /**
             * Target End
             * @description Resolved target period after applying request defaults and availability constraints.
             */
            target_end?: string | null;
            /**
             * Target End Source
             * @description Where target_end came from, for example request, default_today, request_clamped_by_availability, default_today_clamped_by_availability, or current_coverage.
             */
            target_end_source: string;
            /**
             * Delta Start
             * @description First missing period planned for append execution, when applicable.
             */
            delta_start?: string | null;
            /**
             * Delta End
             * @description Last missing period planned for append execution, when applicable.
             */
            delta_end?: string | null;
        };
        /**
         * SyncKind
         * @description Supported sync planning modes declared by dataset templates.
         * @enum {string}
         */
        SyncKind: "temporal" | "release" | "static";
        /**
         * SyncResponse
         * @description Public response returned after planning and optionally running a sync.
         */
        SyncResponse: {
            /**
             * Sync Id
             * @description Identifier of the sync-created version when a new version was written.
             */
            sync_id?: string | null;
            /**
             * Status
             * @description Execution status, for example completed or up_to_date.
             */
            status: string;
            /**
             * Message
             * @description Human-readable explanation of the sync outcome.
             */
            message?: string | null;
            /** @description Current dataset detail. None for async requests. */
            dataset?: components["schemas"]["DatasetDetailRecord"] | null;
            /** @description Planner output describing how Open Climate Service interpreted the sync request. */
            sync_detail?: components["schemas"]["SyncDetail"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowListResponse
         * @description Envelope for GET /process_graphs.
         */
        WorkflowListResponse: {
            /** Processes */
            processes: components["schemas"]["WorkflowRecord"][];
            /** Links */
            links?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * WorkflowRecord
         * @description Persisted workflow (user-defined process).
         */
        WorkflowRecord: {
            /** Id */
            id: string;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            }[];
            /** Returns */
            returns?: {
                [key: string]: unknown;
            } | null;
            /** Process Graph */
            process_graph?: {
                [key: string]: unknown;
            };
            /** Links */
            links?: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Landing page (HTML) or navigation document (JSON) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                    "application/json": {
                        /** Message */
                        message: string;
                        /** Links */
                        links: unknown[];
                        $defs: {
                            /**
                             * Link
                             * @description Hypermedia link.
                             */
                            Link: {
                                /** Href */
                                href: string;
                                /** Rel */
                                rel: string;
                                /** Title */
                                title: string;
                            };
                        };
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    info_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfo"];
                };
            };
        };
    };
    well_known_openeo__well_known_openeo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    credentials_oidc_credentials_oidc_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    file_formats_file_formats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    service_types_service_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_stac_landing_stac_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StacCatalogResponse"];
                };
            };
        };
    };
    get_stac_catalog_json_stac_catalog_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StacCatalogResponse"];
                };
            };
        };
    };
    get_stac_collection_stac_collections__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_collection_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenEOJobListResponse"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenEOJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenEOJobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenEOJobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenEOJobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_jobs__job_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenEOJobResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_jobs__job_id__results_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__results_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_geojson_result_jobs__job_id__results_result_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_zarr_chunk_jobs__job_id__results_result_zarr__zarr_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                zarr_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_result_file_jobs__job_id__results__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_process_graphs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
        };
    };
    get_workflow_process_graphs__process_graph_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_workflow_process_graphs__process_graph_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workflow_process_graphs__process_graph_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_synchronous_result_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extent_extent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtentRecord"];
                };
            };
        };
    };
    list_dataset_templates_dataset_templates__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_dataset_template_dataset_templates__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
        };
    };
    get_dataset_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetailRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_file_datasets__dataset_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_job_ingestions_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_ingestion_job_ingestions_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestions_ingestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionListResponse"];
                };
            };
        };
    };
    create_ingestion_ingestions_post: {
        parameters: {
            query?: never;
            header?: {
                prefer?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_ingestions__ingestion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_canonical_zarr_store_file_zarr__dataset_id___relative_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                relative_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_canonical_zarr_store_file_zarr__dataset_id___relative_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                relative_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_icechunk_store_file_icechunk__dataset_id___file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_icechunk_store_file_icechunk__dataset_id___file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_dataset_sync__dataset_id__post: {
        parameters: {
            query?: never;
            header?: {
                prefer?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncDatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_sync_dataset_sync__dataset_id__plan_get: {
        parameters: {
            query?: {
                end?: string | null;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleListResponse"];
                };
            };
        };
    };
    list_processes_processes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_process_spec_processes__process_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
