export const ALERT_PROGRAM_CODE = "CAPS-ALERT" as const;
export const ALERT_PROGRAM_STAGE_CODE = "CAPS-ALERT-PS";
export const ALERT_THRESHOLD_VALUE_DE_CODE = "CAPS-ALERT-THRESHOLD" as const;
export const ALERT_ACTUAL_VALUE_DE_CODE = "CAPS-ALERT-ACTUAL" as const;
export const ALERT_REPORTING_PERIOD_DE_CODE = "CAPS-ALERT-REPORTING-PERIOD" as const;
export const ALERT_EVENT_STATUS = "COMPLETED" as const;
