import { PrismaClient } from "@db/client.ts";
import { PrismaPg } from "@prisma/adapter-pg";
import { Handlers } from "@/services/worker/constants/handlers.ts";
import type { InputJsonValue } from "@prisma/client/runtime/client";
import { PeriodTypeEnum } from "@hisptz/dhis2-utils";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});

const prisma = new PrismaClient({ adapter });

// ---------------------------------------------------------------------------
// Pipeline definitions
// ---------------------------------------------------------------------------

type StepDef = {
  name: string;
  description: string;
  handlerKey: string;
  stepOrder: number;
  maxRetries: number;
  retryDelayMs: number;
  handlerConfig: Record<string, unknown>;
};

type ScheduleDef = {
  name: string;
  cronExpr: string;
};

type PipelineDef = {
  name: string;
  description: string;
  concurrencyPolicy: "ALLOW" | "SKIP" | "REPLACE";
  isActive: boolean;
  schedules?: ScheduleDef[];
  steps: StepDef[];
};

const pipelines: PipelineDef[] = [
  // --------------------------------------------------------------------------
  // 1. Full climate-disease prediction pipeline
  // --------------------------------------------------------------------------
  {
    name: "ERA5 Climate + CHAP Disease Prediction — Full",
    description:
      "Complete end-to-end pipeline: ingest ERA5 climate data, ingest CHIRPS rainfall, run CHAP disease prediction model, and push results back to DHIS2",
    concurrencyPolicy: "SKIP",
    isActive: true,
    schedules: [{ name: "Daily 06:00", cronExpr: "0 6 * * *" }],
    steps: [],
  },
  // --------------------------------------------------------------------------
  // 2. ERA5 data ingestion only
  // --------------------------------------------------------------------------
  {
    name: "ERA5 Precipitation Climate Ingestion — Standalone",
    description:
      "Fetches and stores ERA5 reanalysis climate data from the Copernicus Climate Data Store. Can run independently to keep climate data fresh without triggering a full prediction run.",
    concurrencyPolicy: "SKIP",
    isActive: true,
    schedules: [{ name: "Daily 04:00", cronExpr: "0 4 * * *" }],
    steps: [
      {
        stepOrder: 3,
        name: "Upload climate data to DHIS2",
        handlerKey: Handlers.DHIS2_DATA_UPLOAD,
        maxRetries: 3,
        retryDelayMs: 15000,
        handlerConfig: {},
        description:
          "Reads the DataValueSet file produced by the previous step (autogenerated filename) and imports it into DHIS2 via POST /dataValueSets",
      },
    ],
  },
  // --------------------------------------------------------------------------
  // 4. CHAP prediction only
  // --------------------------------------------------------------------------
  {
    name: "CHAP Disease Prediction — Standalone",
    description:
      "Runs the CHAP disease prediction model against already-ingested climate data. Use this when climate data is already current and only the prediction step needs to be re-run, for example after a model update.",
    concurrencyPolicy: "SKIP",
    isActive: true,
    steps: [
      {
        stepOrder: 0,
        name: "Run CHAP disease prediction",
        handlerKey: "prediction-trigger",
        maxRetries: 2,
        retryDelayMs: 60000,
        handlerConfig: {
          modelId: "ewars_template",
          name: "EWARS Predictions",
          orgUnit: {
            ids: ["YvLOmtTQD6b"],
            levels: ["3"],
          },
          period: {
            type: PeriodTypeEnum.MONTHLY,
            numberOfPeriodsToGenerate: 3,
            numberPreviousYearsToInclude: 2,
            periodOffset: 15, //15 months
          },
          dataSources: [
            {
              covariate: "population",
              dataElementId: "D8Q6nNeQ7i3",
            },
            {
              covariate: "rainfall",
              dataElementId: "RMaMv7SrUYd",
            },
            {
              covariate: "mean_temperature",
              dataElementId: "Pjd8Rn6mTb0",
            },
            {
              covariate: "disease_cases",
              dataElementId: "tfl5kuK8gVd",
            },
          ],
        },
        description: "Runs the CHAP prediction model to generate district-level disease forecasts",
      },
      {
        stepOrder: 1,
        name: "Run CHAP prediction status",
        handlerKey: Handlers.PREDICTION_POLL,
        maxRetries: 2,
        retryDelayMs: 60000,
        handlerConfig: {},
        description: "Polls the CHAP prediction model for status updates",
      },
      {
        stepOrder: 2,
        name: "Download prediction results",
        handlerKey: Handlers.PREDICTION_DATA_DOWNLOAD,
        maxRetries: 2,
        retryDelayMs: 60000,
        handlerConfig: {
          dataElementIds: {
            "0.1": "z6ozYkqiTV1",
            "0.25": "M1vAlKQgtRf",
            "0.5": "N51dXc31ChF",
            "0.75": "k8CgFW5BBvz",
            "0.9": "N5vaX5HEwFG",
          },
        },
        description: "Downloads the CHAP prediction data for DHIS2 upload",
      },
    ],
  },
  // --------------------------------------------------------------------------
  // 6. Threshold generation — demo pipeline
  // --------------------------------------------------------------------------
  {
    name: "Malaria Threshold Generation — Standalone",
    description:
      "Generates epidemiological alert thresholds for malaria by computing mean+2SD over 5 years of historical monthly case data. Writes a DataValueSet file that the dhis2-data-upload step can push back to DHIS2.",
    concurrencyPolicy: "SKIP",
    isActive: true,
    schedules: [{ name: "Monthly 1st 05:00", cronExpr: "0 5 1 * *" }],
    steps: [
      {
        stepOrder: 0,
        name: "Generate monthly malaria thresholds",
        handlerKey: "threshold-generation",
        maxRetries: 2,
        retryDelayMs: 10000,
        handlerConfig: {
          orgUnit: {
            levels: [3],
          },
          period: {
            years: ["2026"],
            periodType: "Monthly",
            yearsToInclude: 5,
          },
          dataElementIds: ["tfl5kuK8gVd"],
          aggregationType: "SUM",
          calculationMethod: "mean + 2SD",
          outputDataElementId: "Js2E9aBTHxh",
        },
        description:
          "For each district (level 3) and each month in 2023–2024, fetches the same month's case counts for the preceding 5 years and applies mean+2SD to produce an alert threshold value",
      },
      {
        stepOrder: 1,
        name: "Upload malaria thresholds to DHIS2",
        handlerKey: "dhis2-data-upload",
        maxRetries: 3,
        retryDelayMs: 15000,
        handlerConfig: {},
        description:
          "Reads the DataValueSet file produced by the previous step (autogenerated filename) and imports it into DHIS2 via POST /dataValueSets",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Seed
// ---------------------------------------------------------------------------

async function main() {
  for (const def of pipelines) {
    const pipeline = await prisma.pipeline.upsert({
      where: { name: def.name },
      create: {
        name: def.name,
        description: def.description,
        concurrencyPolicy: def.concurrencyPolicy,
        isActive: def.isActive,
      },
      update: {
        description: def.description,
        concurrencyPolicy: def.concurrencyPolicy,
        isActive: def.isActive,
      },
    });

    for (const step of def.steps) {
      await prisma.pipelineStep.upsert({
        where: {
          pipelineId_stepOrder: {
            pipelineId: pipeline.id,
            stepOrder: step.stepOrder,
          },
        },
        create: {
          pipelineId: pipeline.id,
          name: step.name,
          description: step.description,
          handlerKey: step.handlerKey,
          stepOrder: step.stepOrder,
          maxRetries: step.maxRetries,
          retryDelayMs: step.retryDelayMs,
          handlerConfig: step.handlerConfig as InputJsonValue,
        },
        update: {
          name: step.name,
          description: step.description,
          handlerKey: step.handlerKey,
          maxRetries: step.maxRetries,
          retryDelayMs: step.retryDelayMs,
          handlerConfig: step.handlerConfig as InputJsonValue,
        },
      });
    }

    if (def.schedules?.length) {
      for (const schedule of def.schedules) {
        const existing = await prisma.pipelineSchedule.findFirst({
          where: { pipelineId: pipeline.id, name: schedule.name },
        });
        if (existing) {
          await prisma.pipelineSchedule.update({
            where: { id: existing.id },
            data: { cronExpr: schedule.cronExpr, status: "ACTIVE" },
          });
        } else {
          await prisma.pipelineSchedule.create({
            data: {
              pipelineId: pipeline.id,
              name: schedule.name,
              status: "ACTIVE",
              cronExpr: schedule.cronExpr,
            },
          });
        }
      }
    }

    const scheduleCount = def.schedules?.length ?? 0;
    console.log(
      `[seed] "${pipeline.name}" — ${def.steps.length} step(s), ${scheduleCount} schedule(s) seeded`
    );
  }
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
